version: "3.6"
networks:
  app-tier:
    driver: bridge
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - app-tier
    ports:
      - "2181:2181"
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis-master1:
    image: redis
    container_name: redis-master
    working_dir: /config
    ports:
      - "6379:6379"
  elasticsearch:
    image: 'bitnami/elasticsearch:latest'
    networks:
      - app-tier
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
  kibana:
    image: 'bitnami/kibana:latest'
    networks:
      - app-tier
    ports:
      - "5601:5601"